# Generated by Django 5.2.5 on 2025-08-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="toifa_document",
            field=models.FileField(blank=True, null=True, upload_to="toifa_documents/"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="toifa",
            field=models.CharField(
                choices=[
                    ("oliy", "Oliy"),
                    ("1", "1-toifa"),
                    ("2", "2-toifa"),
                    ("mutaxassis", "Mutaxassis"),
                    ("yoq", "Yo'q"),
                ],
                default="yoq",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RegistrationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_step", models.CharField(default="full_name", max_length=50)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("region_id", models.IntegerField(blank=True, null=True)),
                ("district_id", models.IntegerField(blank=True, null=True)),
                (
                    "school_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "toifa",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("oliy", "Oliy"),
                            ("1", "1-toifa"),
                            ("2", "2-toifa"),
                            ("mutaxassis", "Mutaxassis"),
                            ("yoq", "Yo'q"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "toifa_document",
                    models.FileField(
                        blank=True, null=True, upload_to="temp_documents/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_state",
                        to="bot.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registration State",
                "verbose_name_plural": "Registration States",
            },
        ),
    ]
