# Generated by Django 5.2.5 on 2025-08-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_teacher_toifa_document_alter_teacher_toifa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="toifa_document",
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, max_length=20, null=True, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="RegistrationState",
        ),
    ]
