# Generated by Django 5.2.5 on 2025-08-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_remove_teacher_toifa_document_alter_user_telegram_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel_name", models.CharField(max_length=255)),
                ("channel_id", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Channel ID",
                "verbose_name_plural": "Channel IDs",
            },
        ),
    ]
