# Generated by Django 5.2.5 on 2025-09-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_pointscore_linkgot_point_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_by",
            field=models.BigIntegerField(
                blank=True,
                help_text="Telegram ID of user who referred this user",
                null=True,
            ),
        ),
    ]
