# Generated by Django 5.2.5 on 2025-09-01 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0006_user_referral_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="referral_by",
        ),
    ]
