# Generated by Django 5.2.5 on 2025-09-01 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0007_remove_user_referral_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="referral",
            unique_together={("referrer", "referee")},
        ),
    ]
