# Generated by Django 5.2.5 on 2025-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0008_alter_referral_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="toifa",
            field=models.CharField(
                choices=[
                    ("oliy", "Oliy"),
                    ("1", "1-toifa"),
                    ("2", "2-toifa"),
                    ("mutaxassis", "Mutaxassis"),
                ],
                default="mutaxassis",
                max_length=20,
            ),
        ),
    ]
